apiVersion: apps/v1
kind: Deployment
metadata:
  name: azflow-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azflow-api
  template:
    metadata:
      labels:
        app: azflow-api
    spec:
      containers:
        - name: azflow-api
          image: azflow.azurecr.io/azflow-api:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: azflow-api-service
spec:
  selector:
    app: azflow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
