package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"azflow-api/azure/auth"
	"azflow-api/domain/story"
	"azflow-api/graph/model"
	"azflow-api/openai"
	"context"
)

// CreateAudio is the resolver for the createAudio field.
func (r *mutationResolver) CreateAudio(ctx context.Context, input model.AudioInput) (string, error) {
	userId, err := auth.GetUserId(ctx)
	if err != nil {
		return "", err
	}

	return story.CreateAudio(userId, input.Text, input.Voice)
}

// AudioUrls is the resolver for the audioUrls field.
func (r *mutationResolver) AudioUrls(ctx context.Context) ([]string, error) {
	userId, _ := auth.GetUserId(ctx)

	return story.GetAudioUrls(userId)
}

// TrackURL is the resolver for the trackUrl field.
func (r *queryResolver) TrackURL(ctx context.Context) (string, error) {
	return openai.GetTrack(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
