// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Audio struct {
	URL           string `json:"url"`
	TranscriptURL string `json:"transcriptUrl"`
	Title         string `json:"title"`
	ID            int    `json:"id"`
}

type AudioInput struct {
	Text  string `json:"text"`
	Voice string `json:"voice"`
	Title string `json:"title"`
}

type BookInput struct {
	Title string `json:"title"`
}

type EditAudioInput struct {
	ID         int    `json:"id"`
	Title      string `json:"title"`
	Transcript string `json:"transcript"`
}

type Mutation struct {
}

type Query struct {
}

type ShortURL struct {
	ID       string `json:"id"`
	LongURL  string `json:"longURL"`
	ShortURL string `json:"shortURL"`
}

type SignupInput struct {
	ExtID string `json:"extId"`
	Email string `json:"email"`
}
